<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>PerformanceTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SymLinkStorage\SymLinkStorage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\TestSupport\CancellationTokensAccessorMock.cs" Link="CancellationTokensAccessorMock.cs" />
  </ItemGroup>
</Project>
