<Project>
  <ItemGroup Condition="'$(MSBuildProjectExtension)' != '.esproj'">
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.10.48">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
