using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using System.Text;
using System.Text.Json.Serialization;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: ApiTypeScriptGenerator <api-assembly-path> <output-path>");
    return 2;
}

var assemblyPath = Path.GetFullPath(args[0]);
var outputPath = Path.GetFullPath(args[1]);
var assemblyDirectory = Path.GetDirectoryName(assemblyPath)
    ?? throw new InvalidOperationException($"Cannot resolve assembly directory for '{assemblyPath}'.");

AssemblyLoadContext.Default.Resolving += (_, assemblyName) =>
{
    var candidate = Path.Combine(assemblyDirectory, $"{assemblyName.Name}.dll");
    return File.Exists(candidate)
        ? AssemblyLoadContext.Default.LoadFromAssemblyPath(candidate)
        : null;
};

var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(assemblyPath);
var assemblyTypes = GetLoadableTypes(assembly);
var modelTypes = assemblyTypes
    .Where(static type => type is { IsPublic: true, IsNested: false }
        && type.Namespace == "GraphData.Api.Models"
        && (type.IsClass || type.IsInterface))
    .OrderBy(static type => type.Name, StringComparer.Ordinal)
    .ToArray();

var generator = new TypeScriptDtoGenerator(modelTypes);
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)
    ?? throw new InvalidOperationException($"Cannot resolve output directory for '{outputPath}'."));
File.WriteAllText(outputPath, generator.Generate(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
return 0;

static IEnumerable<Type> GetLoadableTypes(Assembly assembly)
{
    try
    {
        return assembly.GetTypes();
    }
    catch (ReflectionTypeLoadException ex)
    {
        return ex.Types.Where(static type => type is not null)!;
    }
}

internal sealed class TypeScriptDtoGenerator
{
    private readonly Type[] modelTypes;
    private readonly NullabilityInfoContext nullability = new();

    public TypeScriptDtoGenerator(Type[] modelTypes)
    {
        this.modelTypes = modelTypes;
    }

    public string Generate()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from GraphData.Api.Models. Do not edit by hand.");
        builder.AppendLine();

        for (var index = 0; index < modelTypes.Length; index++)
        {
            var type = modelTypes[index];
            if (IsPolymorphicBase(type))
            {
                WritePolymorphicAlias(builder, type);
            }
            else
            {
                WriteInterface(builder, type);
            }

            if (index < modelTypes.Length - 1)
                builder.AppendLine();
        }

        return builder.ToString();
    }

    private void WritePolymorphicAlias(StringBuilder builder, Type type)
    {
        var derivedTypes = type.GetCustomAttributes<JsonDerivedTypeAttribute>()
            .Select(static attribute => attribute.DerivedType)
            .Where(static derivedType => derivedType is not null)
            .Select(static derivedType => derivedType!)
            .OrderBy(static derivedType => derivedType.Name, StringComparer.Ordinal)
            .ToArray();

        builder.Append("export type ").Append(TypeScriptName(type)).AppendLine(" =");
        for (var index = 0; index < derivedTypes.Length; index++)
        {
            var suffix = index == derivedTypes.Length - 1 ? ";" : "";
            builder
                .Append("  | ")
                .Append(TypeScriptName(derivedTypes[index]))
                .AppendLine(suffix);
        }
    }

    private void WriteInterface(StringBuilder builder, Type type)
    {
        builder.Append("export interface ").Append(TypeScriptName(type)).AppendLine(" {");

        var discriminator = DiscriminatorFor(type);
        if (discriminator is { } discriminatorValue)
        {
            builder
                .Append("  ")
                .Append(discriminatorValue.PropertyName)
                .Append(": ")
                .Append(StringLiteral(discriminatorValue.Value))
                .AppendLine(";");
        }

        foreach (var property in PublicDtoProperties(type))
        {
            var propertyNullability = nullability.Create(property);
            var propertyType = ToTypeScriptType(property.PropertyType, propertyNullability);
            if (propertyNullability.ReadState == NullabilityState.Nullable && !propertyType.Contains("null", StringComparison.Ordinal))
            {
                propertyType += " | null";
            }

            builder
                .Append("  ")
                .Append(JsonPropertyName(property))
                .Append(IsRequired(property) ? ": " : "?: ")
                .Append(propertyType)
                .AppendLine(";");
        }

        builder.AppendLine("}");
    }

    private IEnumerable<PropertyInfo> PublicDtoProperties(Type type)
    {
        return type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(static property => property.GetMethod is not null
                && property.GetIndexParameters().Length == 0
                && !property.GetCustomAttributes<ObsoleteAttribute>().Any(static obsolete => obsolete.IsError))
            .OrderBy(static property => property.MetadataToken);
    }

    private string ToTypeScriptType(Type type, NullabilityInfo? nullabilityInfo = null)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return "string";

        if (type == typeof(bool))
            return "boolean";

        if (type.IsPrimitive || type == typeof(decimal))
            return "number";

        if (type.IsArray)
        {
            var elementType = type.GetElementType()
                ?? throw new InvalidOperationException($"Cannot resolve element type for '{type}'.");
            return $"{ToTypeScriptType(elementType, nullabilityInfo?.ElementType)}[]";
        }

        if (IsDictionary(type, out var valueType))
            return $"Record<string, {ToTypeScriptType(valueType, nullabilityInfo?.GenericTypeArguments.ElementAtOrDefault(1))}>";

        if (IsEnumerable(type, out var element))
            return $"{ToTypeScriptType(element, nullabilityInfo?.GenericTypeArguments.FirstOrDefault())}[]";

        if (type.Namespace == "GraphData.Api.Models")
            return TypeScriptName(type);

        return "unknown";
    }

    private static bool IsDictionary(Type type, out Type valueType)
    {
        var dictionary = type
            .GetInterfaces()
            .Append(type)
            .FirstOrDefault(static candidate => candidate.IsGenericType
                && (candidate.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)
                    || candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>))
                && candidate.GetGenericArguments()[0] == typeof(string));

        valueType = dictionary?.GetGenericArguments()[1] ?? typeof(object);
        return dictionary is not null;
    }

    private static bool IsEnumerable(Type type, out Type elementType)
    {
        if (type == typeof(string))
        {
            elementType = typeof(char);
            return false;
        }

        var enumerable = type
            .GetInterfaces()
            .Append(type)
            .FirstOrDefault(static candidate => candidate.IsGenericType
                && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));

        elementType = enumerable?.GetGenericArguments()[0] ?? typeof(object);
        return enumerable is not null;
    }

    private static bool IsPolymorphicBase(Type type)
    {
        return type.IsAbstract && type.GetCustomAttributes<JsonDerivedTypeAttribute>().Any();
    }

    private (string PropertyName, string Value)? DiscriminatorFor(Type type)
    {
        var baseType = type.BaseType;
        while (baseType is not null && baseType != typeof(object))
        {
            var derivedType = baseType
                .GetCustomAttributes<JsonDerivedTypeAttribute>()
                .FirstOrDefault(attribute => attribute.DerivedType == type);
            if (derivedType is not null)
            {
                var propertyName = baseType.GetCustomAttribute<JsonPolymorphicAttribute>()?.TypeDiscriminatorPropertyName ?? "$type";
                var value = derivedType.TypeDiscriminator?.ToString() ?? type.Name;
                return (propertyName, value);
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static bool IsRequired(PropertyInfo property)
    {
        return property.GetCustomAttribute<RequiredMemberAttribute>() is not null;
    }

    private static string JsonPropertyName(PropertyInfo property)
    {
        return property.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? ToCamelCase(property.Name);
    }

    private static string TypeScriptName(Type type)
    {
        var name = type.Name;
        var tickIndex = name.IndexOf('`', StringComparison.Ordinal);
        return tickIndex >= 0 ? name[..tickIndex] : name;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsLower(name[0]))
            return name;

        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private static string StringLiteral(string value)
    {
        return "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
    }
}
