<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\TestImpactOnCoverage\src\RelevantTests.MSTest\build\RelevantTests.MSTest.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>DomainTests</AssemblyName>
    <RelevantTestsCurrentRoot>$(MSBuildProjectDirectory)\..</RelevantTestsCurrentRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.3.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.3.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="RelevantTests.MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SymLinkStorage\SymLinkStorage.csproj" />
    <ProjectReference Include="..\TestImpactOnCoverage\src\RelevantTests.MSTest\RelevantTests.MSTest.csproj" />
  </ItemGroup>

  <ItemGroup>
    <RelevantTestsTargetProject Include="..\Abstractions\Abstractions.csproj" TargetAssembly="Abstractions" />
    <RelevantTestsTargetProject Include="..\Domain\Domain.csproj" TargetAssembly="Domain" />
    <RelevantTestsTargetProject Include="..\SymLinkStorage\SymLinkStorage.csproj" TargetAssembly="SymLinkStorage" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestSupport\CancellationTokensAccessorMock.cs" Link="CancellationTokensAccessorMock.cs" />
    <Compile Include="..\TestSupport\TestGraphStorageScope.cs" Link="TestGraphStorageScope.cs" />
  </ItemGroup>

  <Import Project="..\TestImpactOnCoverage\src\RelevantTests.MSTest\build\RelevantTests.MSTest.targets" />
</Project>
